### ISSUE TITLE
Font Suggestion

### ISSUE THREAD

**Issue by xstyyy** [Rairof/Theme-Fonts#1]
Hello, here are a few fonts you could maybe add:
- [x] [Inter](https://fonts.google.com/specimen/Inter?category=Monospace&icon.set=Material+Symbols&query=inter)
- [x] [Instrument Sans](https://fonts.google.com/specimen/Instrument+Sans?query=sans&subset=latin&noto.script=Latn)
- [x] [Golos Text](https://fonts.google.com/specimen/Golos+Text?icon.set=Material+Symbols&category=Sans+Serif&subset=latin&noto.script=Latn)
- [x] [Gantari](https://fonts.google.com/specimen/Gantari?icon.set=Material+Symbols&category=Sans+Serif&subset=latin&noto.script=Latn&stroke=Sans+Serif)
- [x] [Almarai](https://fonts.google.com/specimen/Almarai?icon.set=Material+Symbols&category=Sans+Serif)

Also maybe you could provide fonts for codeblocks as well, here are some suggests of mine as well:
- [x] [JetBrains Mono](https://fonts.google.com/specimen/JetBrains+Mono?icon.set=Material+Symbols&category=Sans+Serif&subset=latin&noto.script=Latn&query=Jetbrains+mono)
- [x] [Space Mono](https://fonts.google.com/specimen/Space+Mono?icon.set=Material+Symbols&category=Sans+Serif&subset=latin&noto.script=Latn&query=Space+mono)
- [x] [Fira Code](https://fonts.google.com/specimen/Fira+Code?icon.set=Material+Symbols&category=Sans+Serif&subset=latin&noto.script=Latn&classification=Monospace)
- [x] [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro?icon.set=Material+Symbols&category=Sans+Serif&subset=latin&noto.script=Latn&classification=Monospace&query=Source+code+pro)
- [x] [Ubuntu Mono](https://fonts.google.com/specimen/Ubuntu+Mono?icon.set=Material+Symbols&category=Sans+Serif&subset=latin&noto.script=Latn&classification=Monospace&query=ubuntu+mono)

**Comment by Rairof** [comment]
Will do! Thanks for your suggestion! ♥️

**Comment by Rairof** [comment]
All fonts have been added!
you can change codeblock fonts by changing the font link in the `SourceCodePro-Semibold` string into whatever font you like.

**Comment by xstyyy** [comment]
Sounds good! Thank you so much for adding the suggested fonts
