### ISSUE TITLE
some links broken

### ISSUE THREAD

**Issue by moonfight1** [Rairof/Theme-Fonts#7]
for example in the Evolve sans EVO font json some links have a dash between Evolve and sans despite the file not having it

**Comment by Rairof** [comment]
I might have missed that. I also fixed a couple more font file names having similar typos. Thanks for pointing it out.

**Comment by moonfight1** [comment]
oh i thought i was going insane when i looked again and saw nothing (thats why i closed the issue), thanks lol

**Comment by Rairof** [comment]
I thought I would fix this one small issue and finish off but I ended up fixing many other things and ended up fixing all issues I had on my list I noted down before. Thank you for getting me out of my procrastination state with this issue post.

**Comment by moonfight1** [comment]
you're welcome ig
